spring:
  application:
    name: demo-effective-jpa
    admin:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8080/effective-jpa/admin
        instance:
          name: ${spring.application.name}
          prefer-ip: true
      server:
        enabled: true
      context-path: /admin
  config:
    import:
      - classpath:application-database.yaml
      - classpath:application-ops.yaml
server:
  servlet:
    context-path: /effective-jpa
