spring:
  application:
    name: demo-effective-jpa
    admin:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8080/effective-jpa
        instance:
          name: ${spring.application.name}
          prefer-ip: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    startup:
      enabled: true
server:
  servlet:
    context-path: /effective-jpa

